# Stage 1
FROM node:16-alpine as ts-compiler

RUN mkdir -p /usr/app
WORKDIR /usr/app

COPY package.json ./
COPY tsconfig.json ./
RUN npm install
COPY . ./

RUN npm run build

# Stage 2
FROM node:16-alpine as ts-remover

WORKDIR /usr/app

COPY --from=ts-compiler /usr/app/package.json ./
COPY --from=ts-compiler /usr/app/build ./

RUN npm install --omit=dev

#stage 3
FROM gcr.io/distroless/nodejs:16

WORKDIR /usr/app
COPY --from=ts-remover /usr/app ./

USER 1000
CMD ["main.js"]
